{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.espresso",
    "module": "espresso_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c29809135135e262a912cf583b2c90deb9ded610"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "runner",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "rules",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "truth",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.4.5"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-contrib",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-intents",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-accessibility",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-web",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "androidx.test.espresso.idling",
          "module": "idling-concurrent",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-idling-resource",
          "version": {
            "requires": "3.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "espresso_debug-1.0.aar",
          "url": "espresso_debug-1.0.aar",
          "size": 86324,
          "sha512": "2808dba45005de9db2c2bc45a4539dd41f5e91119d2b29acb0b0d3f5349011025185e15f6a1bf1d68679eb6f0e4024453724c7656232626f953556e299eeadaf",
          "sha256": "4340fad9d938d0e94b4b3c338bfb40bed4a4eae6c6c6038d9da3445689ca899d",
          "sha1": "0c99c1c4a52658dc805c28bbad8a4f4757c70c45",
          "md5": "b48f1d2b6015d0dfadadc4e34f3afda4"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c29809135135e262a912cf583b2c90deb9ded610"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.5.0-android"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "runner",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "rules",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "truth",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.4.5"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-contrib",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-intents",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-accessibility",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-web",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "androidx.test.espresso.idling",
          "module": "idling-concurrent",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-idling-resource",
          "version": {
            "requires": "3.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "espresso_debug-1.0.aar",
          "url": "espresso_debug-1.0.aar",
          "size": 86324,
          "sha512": "2808dba45005de9db2c2bc45a4539dd41f5e91119d2b29acb0b0d3f5349011025185e15f6a1bf1d68679eb6f0e4024453724c7656232626f953556e299eeadaf",
          "sha256": "4340fad9d938d0e94b4b3c338bfb40bed4a4eae6c6c6038d9da3445689ca899d",
          "sha1": "0c99c1c4a52658dc805c28bbad8a4f4757c70c45",
          "md5": "b48f1d2b6015d0dfadadc4e34f3afda4"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "espresso_debug-1.0-sources.jar",
          "url": "espresso_debug-1.0-sources.jar",
          "size": 64074,
          "sha512": "bfd6af79b9f13ec3e7639049919b85f2adc9acb0669fc20c68724d1c1635fe8e288ee5ae1d4ba3b70bd57c6246d86a8e266538d6e810b19f000c4b3b7e87c352",
          "sha256": "2d09a2de426776469732993cdb06ae011abe16d13d1944418329ed562fe67cc9",
          "sha1": "6677919179013341c75d0883c2d02376940f40ab",
          "md5": "cc03ff92777cce9dad438baf5e5ad509"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "espresso_debug-1.0-javadoc.jar",
          "url": "espresso_debug-1.0-javadoc.jar",
          "size": 475032,
          "sha512": "bd8dc5463728ff861c6e45b43f39e0afc59086149d98fff9aca1328feddf391e963e31f83b5380e697f0a18099a39cf1404f37cec7451821f5d4a1f1693f7d47",
          "sha256": "b4249752dda0a6cb2f810dc062ccebaeefdf3313900c1a42aa63410f8e176a9c",
          "sha1": "dd06394676c5e3f4668355acb5e1132dfed639ec",
          "md5": "b4c8a836c13a0ae7a769f955eeec9bd7"
        }
      ]
    }
  ]
}
