{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.nabrajkhadka.example.flutter_module",
    "module": "flutter_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c29809135135e262a912cf583b2c90deb9ded610"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-c29809135135e262a912cf583b2c90deb9ded610"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-c29809135135e262a912cf583b2c90deb9ded610"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-c29809135135e262a912cf583b2c90deb9ded610"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 5879972,
          "sha512": "326205f29d2494097fd7aa4545b8ccb080c7fb3b45838726031e83c4daf92198549fcc28a7432385935b4ae07662cd8465aa1eec969e912492565bc4f6b3d484",
          "sha256": "a9a30bff68cbc8b471d7e4c8d336def092f35baa831eb008394a8645f4ea2c53",
          "sha1": "7d6fa3fe3e60f384f2e772b04261092869cff15d",
          "md5": "cf46ff932647dd60fcb58565a920257b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c29809135135e262a912cf583b2c90deb9ded610"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-c29809135135e262a912cf583b2c90deb9ded610"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-c29809135135e262a912cf583b2c90deb9ded610"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-c29809135135e262a912cf583b2c90deb9ded610"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 5879972,
          "sha512": "326205f29d2494097fd7aa4545b8ccb080c7fb3b45838726031e83c4daf92198549fcc28a7432385935b4ae07662cd8465aa1eec969e912492565bc4f6b3d484",
          "sha256": "a9a30bff68cbc8b471d7e4c8d336def092f35baa831eb008394a8645f4ea2c53",
          "sha1": "7d6fa3fe3e60f384f2e772b04261092869cff15d",
          "md5": "cf46ff932647dd60fcb58565a920257b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.0-sources.jar",
          "url": "flutter_release-1.0-sources.jar",
          "size": 1008,
          "sha512": "6ac6436640930885931051b8fac4aa27f8a847d33e9b96f7e4d8f422aec9ff627670e26ba860e90a5c8c34771ade8d2e0b6a9090b2e46e13082465d6b00ecf72",
          "sha256": "0b75aba57699df30f0bac04dfcc4d000c9b1c96130d09e2346e753cb8f55518e",
          "sha1": "75379ad607250ff70d501d22dd660929347193d5",
          "md5": "a730f69ca4df125c3b9d3a5416b60d6d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.0-javadoc.jar",
          "url": "flutter_release-1.0-javadoc.jar",
          "size": 261616,
          "sha512": "5b64cd42625ec2c75c9437f18bd3e5c69969556ad3c068ca7bd0242f8c7d23ce6c65d2f8097e005e229d5f241d05929b5c0bf94caa334d45fd2f8e456b2c347f",
          "sha256": "3c5197d7e5a0df80632c6be2dcc3d32fe22a7c0acd3b7be2fa4d01973e5759b0",
          "sha1": "acd5578a961c4af43f01bb0d35115becc8c2d530",
          "md5": "4fdbf6eb2ad0e81958a11cf3a2e9d327"
        }
      ]
    }
  ]
}
